#!/usr/bin/env bash
# Bash script that configures nginx on a new Ubuntu machine
sudo apt-get -y update

# install nginx
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
