#!/usr/bin/env bash
# configures an Nginx server to have a custom 404 page that contains the string 'Ceci n'est pas une page'
sudo apt-get -y update

# install nginx
sudo apt-get -y install nginx

hostname="$(cat /etc/hostname)"

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default

sudo sed -i "/try_files \$uri \$uri\/ =404;/i \ \ \ \ \ \ \ \ add_header X-Served-By \"$hostname\";" /etc/nginx/sites-available/default

sudo service nginx restart
