#!/usr/bin/env bash
# Install and configure HAproxy so that it send traffic to web-01 and web-02
sudo apt -y update

# install HAproxy
sudo apt -y install haproxy

haproxy_cfg="/etc/haproxy/haproxy.cfg"
web_01="54.90.42.213"
web_02="100.26.56.169"

# Backup the original configuration file
sudo cp "$haproxy_cfg" "$haproxy_cfg.bak"

echo "
global
    log /dev/log local0
    log /dev/log local1 notice
    maxconn 4096
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server server1 $web_01:80 check
    server server2 $web_02:80 check
" | sudo tee "$haproxy_cfg"

# Restart HAProxy
sudo service haproxy restart
