#!/usr/bin/env bash
# This script displays numbers from 1 to 100 with FizzBuzz.
i=1
while [ $i -lt 101 ]
do
  if [ $((i % 15)) -eq 0 ]; then
    echo "FizzBuzz"
  elif [ $((i % 5)) -eq 0 ]; then
    echo "Buzz"
  elif [ $((i % 3)) -eq 0 ]; then
    echo "Fizz"
  else
    echo $i
  fi
  i=$((i + 1))
done
