#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while loop and Hi on 9th iteration
i=1
while [ $i -lt 11 ]
do
  echo "Best School"
  if [ $i -eq 9 ]; then
    echo "Hi"
  fi
  i=$((i + 1))
done
